# Generated by Django 4.0.2 on 2022-03-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolistapp', '0002_task_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date_due',
        ),
        migrations.RemoveField(
            model_name='task',
            name='date_scheduled',
        ),
        migrations.RemoveField(
            model_name='task',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='task',
            name='list',
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.DeleteModel(
            name='List',
        ),
    ]
